"""EDF ECS naming reference.

Source: ``[28] ENSIRM0100021 A - Codification ECS.pdf``.
"""

from types import MappingProxyType

from parc.utils.types import StrEnum


class ElementarySystems(StrEnum):
    """Top-level ECS functional sets."""

    A = "Alimentation en eau - poste d'eau"
    B = "Manutention, stockage des combustibles et de leurs résidus"
    C = "Condensation, refroidissement (condenseur)"
    D = "Systèmes annexes non importants pour la production (divers)"
    E = "Enceinte de confinement"
    F = "Chaudière (combustion, générateur de vapeur)"
    G = "Groupe turboalternateur et évacuation d'énergie"
    H = "Bâtiments"
    J = "Incendie"
    K = "Contrôle"
    L = "Distribution électrique"
    P = "Piscine de stockage du combustible"
    R = "Réacteur"
    S = "Services généraux liés à la production"
    T = "Traitement des effluents"
    V = "Circuit vapeur principal"
    X = "Production vapeur auxiliaire"
    Y = "Installations d'essai"


FUNCTIONAL_SET_CODES = MappingProxyType({system.name: system.value for system in ElementarySystems})

ELEMENTARY_SYSTEM_FAMILIES = MappingProxyType(
    {
        "DA*": "Ascenseurs et monte-charges",
        "DC*": "Ventilation - conditionnement",
        "DE*": "Eau glacée (production et distribution)",
        "DF*": "Désenfumage (si indépendant de la ventilation)",
        "DM*": "Appareils et engins de manutention",
        "DN*": "Eclairage normal du site, bâtiments et surfaces ouvertes",
        "DS*": "Eclairage de secours du site, bâtiments et surfaces ouvertes",
        "DT.": "Téléphone, transmission et télétransmission",
        "DV*": "Ventilation - conditionnement (non contaminable)",
        "DW*": "Ventilation - désenfumage - conditionnement",
        "GD.": "Groupe à moteurs thermiques (diesels..)",
        "GZ": "Groupes turbines à combustion",
        "JA.": "Production eau d'incendie",
        "JD.": "Détection incendie",
        "JG*": "Protection incendie par gaz inerte",
        "JP.": "Protection incendie et distribution eau incendie",
        "KA.": "Aide à l'exploitation (conduite et maintenance)",
        "KC.": "Matériel de contrôle commande (logique et analogique)",
        "KG.": "Système informatique de gestion",
        "KI.": "Systèmes informatiques de conduite (de commande et surveillance)",
        "KK.": "Contrôle accès",
        "KL.": "Réseau informatique",
        "KR.": "Mesure d'ambiance",
        "KS.": "Salle de commande - panneaux de repli - et pupitres",
        "KT.": "Instrumentation spéciale indépendante",
        "KZ.": "Système informatique de surveillance ou commande à distance",
        "LA.": "Production et distribution puissance 230V continu",
        "LB.": "Production et distribution équipement 125 V continu",
        "LC.": "Production et distribution relayage 48 V continu",
        "LD.": "Production et distribution régulation 30V continu",
        "LE.": "Production et distribution régulation 24 V continu",
        "LG.": "Distribution > ou = à 5,5 kV alternatif (non secouru)",
        "LH#": "Courant alternatif > ou = à 5,5 kV secouru",
        "LI.": "Distribution 690 V alternatif normal",
        "LJ.": "Distribution 690 V alternatif secouru",
        "LK.": "Distribution 400 V alternatif normal (sous tableau LG)",
        "LL#": "Distribution 400 V alternatif secouru (sous tableau LH)",
        "LM.": "Distribution 220 V alternatif non régulée",
        "LN.": "Production et distribution 220 V alternatif sans coupure",
        "LO.": "Distribution 400V alternative régulée",
        "LP.": "Distribution 110 V alternatif non secouru",
        "LQ.": "Distribution 110 V alternatif secouru",
        "LR.": "Distribution 20 kV alternatif (10 kV selon les sites)",
        "LS.": "Boucles d'essai",
        "LV.": "Production et distribution 400V sans coupure",
        "LY.": "Circuit d'essai",
        "SA.": "Production et distribution d'air",
        "SB.": "Bloc entretien chaud",
        "SD.": "Eau déminéralisée (production - traitement - distribution - stockage)",
        "SE.": "Distribution et traitement de l'eau (sauf eau déminéralisée)",
        "SF.": "Filtration",
        "SG.": "Distribution fluide autre que eau et air",
        "SI.": "Chimie, réactifs et traitements",
        "SK.": "Stockage fluides autres que eau et air",
        "SM.": "Traitement des engins de manutention",
        "SN.": "Traitement par le vide nettoyage",
        "SP.": "Protection",
        "SR.": "Réfrigération",
        "ST.": "Traçage",
        "SV.": "Vapeur auxiliaire",
    }
)

ELEMENTARY_SYSTEM_CODES = MappingProxyType(
    {
        "ABP": "Poste d'eau basse pression et réchauffeurs",
        "ACA": "Alimentation en eau depuis l'entrée économiseur jusqu'au ballon y compris les pompes de circulation assistée",
        "ACO": "Reprise des condensats du poste d'eau",
        "ADA": "Ensemble motopompe alimentaire de démarrage et d'arrêt",
        "ADG": "Alimentation et dégazage (bâche et dégazeur)",
        "AFR": "Fluide de régulation turbopompe alimentaire",
        "AGR": "Graissage soulèvement virage turbopompe alimentaire",
        "AHP": "Poste d'eau haute pression, moyenne pression et réchauffeurs",
        "APA": "Ensemble motopompe alimentaire (y compris graissage)",
        "APG": "Purge générateur de vapeur (chaudière)",
        "APP": "Ensemble turbopompe alimentaire",
        "ARE": "Alimentation normale des générateurs de vapeur",
        "ASG": "Alimentation auxiliaire de secours des GV",
        "ATH": "Traitement d'huile turbopompe alimentaire",
        "BAC": "Alimentation charbon vers la chaudière",
        "BDC": "Décrasseur",
        "BED": "Stockage et évacuation des refus broyeurs",
        "BEH": "Evacuation hydraulique des suies et machefers",
        "BEM": "Evacuation machefers stockage destockage",
        "BES": "Evacuation et stockage des suies sèches",
        "BKE": "Dépotage stockage fioul usine (engins manutention appareil chauffage)",
        "BKI": "Dépotage stockage fioul domestique",
        "BKO": "Dépotage stockage fioul lourd",
        "BKP": "Stockage gaz (propane)",
        "BMC": "Déchargement stockage et reprise sur parc",
        "BSC": "Stockage calcaire",
        "BSG": "Stockage gypse humide",
        "BSH": "Reprise et évacuation gypse humide",
        "BSP": "Injection et résidu des produits de désulfuration primaire (injection au foyer)",
        "BSS": "Injection et résidu des produits de désulfuration secondaire (traitement des fumées)",
        "BVF": "Voies ferrées",
        "CDI": "Eau de dilution - Refroidissement des rejets",
        "CET": "Etanchéité labyrinthes turbine et turbopompe alimentaire",
        "CEX": "Circuit d'extraction (pompe de reprise)",
        "CPA": "Protection cathodique",
        "CRF": "Circulation eau (graissage, filtration et isolement)",
        "CTA": "Nettoyage du faisceau condenseur (taprogge, technos)",
        "CTE": "Traitement eau de circulation",
        "CTF": "Vaccination acide des réfrigérants",
        "CVF": "Réfrigérants atmosphériques - Ventilation forcée",
        "CVG": "Circuit de vide galeries station de pompage",
        "CVI": "Vide condenseur",
        "CVP": "Réfrigération des purges des réfrigérants atmosphériques",
        "DTD": "Transport pneumatique de documents",
        "DTE": "Transport pneumatique des échantillons",
        "DTF": "Réseau informatique ((bureautique)",
        "DTL": "Distribution de télévision en circuit fermé",
        "DTV": "Transmission - téléphone - recherche de personnes - distribution de l'heure",
        "EAS": "Aspersion - recirculation de l'aspersion",
        "EAU": "Instrumentation de l'enceinte (auscultations )",
        "EBA": "Balayage du Bâtiment Réacteur",
        "EDE": "Mise en dépression de l'espace entre enceinte",
        "ENC": "Noyage du corium",
        "EPP": "Etanchéité et contrôle des fuites de l'enceinte (sas, traversées, tampons...)",
        "ETY": "Contrôle H2 en cas d'APRP et d'accident grave",
        "EVF": "Filtration interne",
        "EVR": "Ventilation continue bâtiment réacteur",
        "EVU": "Evacuation de chaleur du bâtiment réacteur",
        "FAR": "Air de refroidissement du contrôle de flamme",
        "FBU": "Contrôle flamme (caméra + cellule)",
        "FCA": "Air de combustion (soufflage)",
        "FCR": "Cannes rétractiles",
        "FDA": "Désox recirculation absorbeur",
        "FDB": "Désox alimentations absorbeur",
        "FDG": "Désox centrifugation",
        "FDP": "Désox purge de l'absorbeur",
        "FDR": "Désox réchauffage des fumées désul furées",
        "FDT": "Désox tirage additionnel",
        "FEU": "Enveloppe physique de la chaudière (trappe, trou d'homme, poste, regards)",
        "FFU": "Traitement des fumées (dépoussiéreurs désenfumeurs)",
        "FGA": "Brûleurs d'allumage (démarrage)",
        "FGC": "Brûleurs de charge ou de soutien",
        "FGI": "Torches pilotes",
        "FKP": "Alimentation gaz",
        "FMA": "Air d'étanchéité broyeurs",
        "FOA": "Broyeurs",
        "FPA": "Préchauffeurs d'air",
        "FPI": "Poste préparation fioul domestique",
        "FPO": "Poste de préparation fioul lourd",
        "FRA": "Réchauffeur d'air régénératif",
        "FRM": "Ramonage",
        "FRT": "Reprise égoutture",
        "FSA": "Air primaire commun",
        "FTA": "Tirage (circuit d'air de combustion)",
        "FTC": "Essais de cannes de brûleurs (banc de nettoyage)",
        "FYA": "Recyclage (ventilation recyclage des fumées ou air chaud)",
        "GBP": "Contournement turbine BP (MP)",
        "GCA": "Conservation de la turbine à l'arrêt",
        "GCT": "Contournement turbine condenseur",
        "GDA": "Génératrice asynchrone",
        "GDG": "Circuit d'huile",
        "GDK": "Circuit combustible",
        "GDM": "Groupes électrogènes principaux",
        "GEA": "Transformateur auxiliaire",
        "GEV": "Evacuation d'énergie (transfo soutirage inclus)",
        "GEX": "Excitation et régulation alternateur",
        "GFR": "Fluide de régulation turbine",
        "GGR": "Graissage - soulèvement – virage",
        "GHE": "Huile d'étanchéité alternateur",
        "GHP": "Contournement turbine HP",
        "GME": "Eléments mesure turbine",
        "GPA": "Protection alternateur et évacuation d'énergie",
        "GPV": "Circuits principaux de vapeur turbine et purges",
        "GRE": "Réglage et contrôle turbine",
        "GRH": "Réfrigération de l'alternateur (air ou hydrogène)",
        "GRV": "Remplissage - vidange - appoint H2",
        "GSE": "Sécurités turbine (protections)",
        "GSS": "Sécheurs surchauffeurs",
        "GST": "Eau stator",
        "GTH": "Traitement d'huile",
        "GTR": "Téléréglage - télémesures – comptage",
        "GZA": "Admission d'air de la turbine - système anti-givrage",
        "GZD": "Système de démarrage turbine",
        "GZE": "Echappement turbine",
        "GZI": "Alimentation des injecteurs en fioul domestique",
        "GZL": "Lavage compresseur",
        "GZO": "Injection d'eau déminéralisée - réduction Nox",
        "GZP": "Système d'alimentation en gaz",
        "GZV": "Turbo alternateur (réfrigération, ventilation, sécurité, chambre à combustion)",
        "JAC": "Production eau incendie classée",
        "JAN": "Production eau incendie non classée",
        "JDT": "Détection incendie",
        "JPD": "Protection et distribution eau incendie îlot conventionnel",
        "JPH": "Protection et distribution eau incendie cuves à huile Salle des Machines",
        "JPI": "Protection et distribution eau incendie îlot nucléaire",
        "JPL": "Protection et distribution eau incendie du bâtiment électrique",
        "JPN": "Protection et distribution eau incendie du bloc usine",
        "JPQ": "Protection et distribution eau incendie du bâtiment de traitement des effluents",
        "JPS": "Protection et distribution eau incendie de site",
        "JPT": "Protection et distribution eau incendie des transformateurs",
        "JPV": "Protection et distribution eau incendie Diesels",
        "KAC": "Aide à la consignation",
        "KBS": "Boîte de soudure froide (mesure analogique)",
        "KCC": "Télétransmission avec CNC (Centres Nationaux de Crise)",
        "KCM": "Surveillance des matériels de contrôle-commande de la salle des machine",
        "KCO": "Matériels de contrôle - commande centralisés (automate et traitement)",
        "KCU": "Surveillance des matériels de contrôle-commande de la station de pompage",
        "KDO": "Système d'acquisition de données",
        "KIC": "Système informatique de conduite",
        "KIF": "Contrôle informatique de fonctionnement",
        "KIR": "Instrumentation de surveillance du circuit primaire",
        "KIT": "Traitement des informations (TCI) (traitement centralisé de l'information)",
        "KKK": "Contrôle général des accès",
        "KKV": "Surveillance vidéo de site",
        "KLE": "Réseau local d'entreprise",
        "KLI": "Réseau local industriel",
        "KME": "Acquisition de mesure pour essai périodique",
        "KOS": "Oscillo perturbographie",
        "KPE": "Tachy perturbographie",
        "KRA": "Mesures séisme",
        "KRC": "Contrôle de contamination corporelle et dosimétrique",
        "KRG": "Régulation générale",
        "KRH": "Détection hydrogène îlot nucléaire",
        "KRS": "Contrôle de pollution (radioprotection - météorologie – pollution)",
        "KRT": "Mesure de santé (radioprotection tranche)",
        "KSA": "Traitement des alarmes",
        "KSC": "Instrumentation salle de Commande",
        "KSD": "Système de surveillance et de diagnostic(PSAD)",
        "KSR": "Panneau de repli",
        "KSU": "Platine de sauvegarde et d'alerte",
        "KTC": "Contrôle du combustible",
        "KTF": "Contrôle de la composition des fumées",
        "KTG": "Auscultation table de groupe et réfrigérants atmosphériques",
        "KTR": "Contrôle des résidus et coproduits de combustion",
        "KZC": "Centre national de crise",
        "KZR": "Calculateur d'interface de tranche CASOAR",
        "LHP": "Diesel division 1 (> ou = à 5,5 kV)",
        "LHQ": "Diesel division 2 (> ou = à 5,5 kV)",
        "LHR": "Diesel division 3 (> ou = à 5,5 kV)",
        "LHS": "Diesel division 4 (> ou = à 5,5 kV)",
        "LJP": "Diesel de secours 690V division 1",
        "LJS": "Diesel de secours 690V division 4",
        "LLP": "Diesel 400 V alternatif voie A",
        "LLQ": "Diesel 400 V alternatif voie B",
        "LTR": "Circuit de terre",
        "LYS": "Circuit d'essai de batteries",
        "PMB": "Manutention emballage du combustible",
        "PMC": "Manutention du combustible - machine de chargement - ponts passerelle et auxiliaire",
        "PME": "Postes d'examen du combustible neuf et usagé",
        "PMG": "Machine à serrer et desserrer les goujons",
        "PML": "Eclairage immergé",
        "PMO": "Outillage de manutention",
        "PMT": "Manutention du combustible : transfert et ascenseur",
        "PTR": "Traitement et refroidissement d'eau des piscines",
        "RAM": "Alimentation des mécanismes des grappes",
        "RBS": "Borication de sécurité",
        "RCP": "Circuit primaire",
        "RCV": "Contrôle chimique et volumétrique",
        "REA": "Appoint eau et bore",
        "REN": "Echantillonnage nucléaire",
        "RGL": "Commandes des grappes longues",
        "RIC": "Instrumentation interne du cœur",
        "RIS": "Injection de sécurité",
        "RPE": "Purges, évents et exhaures nucléaires",
        "RPN": "Mesure de la puissance nucléaire",
        "RPR": "Protection réacteur",
        "RRA": "Réfrigération à l'arrêt",
        "RRI": "Réfrigération intermédiaire",
        "RRM": "Ventilation de refroidissement des mécanismes de grappes",
        "SAA": "Production air respirable",
        "SAO": "Production d'air d'oxydation DESOX",
        "SAP": "Production air comprimé de travail et de régulation",
        "SAR": "Distribution air comprimé de régulation",
        "SAT": "Distribution air comprimé de travail",
        "SAX": "Moyen de conservation à l'arrêt",
        "SBE": "Equipement du bloc entretien chaud du site y compris la laverie de site",
        "SDA": "Production d'eau déminéralisée",
        "SDB": "Traitement des boues de la déminéralisation",
        "SDD": "Distribution eau déminéralisée réacteur (stockage inclus)",
        "SDR": "Distribution eau déminéralisée Ph9 installation conventionnelle (stockage inclus)",
        "SDX": "Stockage des produits chimiques et de neutralisation des effluents de la déminéralisation",
        "SEA": "Eau à déminéraliser (pré-traitement)",
        "SEB": "Eau brute",
        "SEC": "Eau brute secourue (réfrigération intermédiaire RRI)",
        "SEF": "Prise d'eau- filtration- degrilleurs",
        "SEG": "Recueil et stockage de solution de gypse DESOX",
        "SEH": "Recueil des huiles et des effluents hydrocarbonés (stockage inclus)",
        "SEI": "Eaux industrielles",
        "SEJ": "Traitement des effluents hydrocarbonnés",
        "SEK": "Recueil, contrôle et rejet des effluents du circuit secondaire",
        "SEN": "Eau brute réfrigération SRI",
        "SEO": "Eaux perdues à l'égout",
        "SEP": "Eau potable",
        "SEQ": "Stockage et distribution eau propre",
        "SES": "Eau surchauffée",
        "SET": "Fourniture d'eau tiède à usage extérieur",
        "SEU": "Eau pluviale (collecte)",
        "SEV": "Traitement des rejets de désulfuration (Desox)",
        "SEW": "Traitement des rejets chaufferies (eaux cendreuses)",
        "SEZ": "Nappe phréatique (rabattement)",
        "SFI": "Filtration eau brute",
        "SGA": "Distribution d'argon",
        "SGC": "Distribution gaz carbonique",
        "SGH": "Distribution d'hydrogène",
        "SGL": "Distribution d'huile",
        "SGN": "Distribution d'azote",
        "SGO": "Distribution d'oxygène",
        "SIC": "Préparation lait calcaire (DESOX)",
        "SIR": "Conditionnement chimique (injection réactif)",
        "SIT": "Contrôle chimique (échantillonnage)",
        "SKA": "Stockage argon",
        "SKC": "Stockage gaz carbonique",
        "SKH": "Stockage hydrogéne",
        "SKL": "Stockage huile",
        "SKN": "Stockage d'azote",
        "SKO": "Stockage oxygène",
        "SKR": "Remplissage-vidange huile moteur des pompes primaires",
        "SKZ": "Stockage des gaz (H2, O2, N2, CO2 et gaz rares)",
        "SMW": "Dégelage des wagons et engins de manutention",
        "SNE": "Neutralisation des effluents de site",
        "SNL": "Nettoyage – lançage GV",
        "SNV": "Nettoyage par le vide de la salle des machines",
        "SRI": "Réfrigération intermédiaire - circuits conventionnels (NORIA)",
        "STE": "Traçage électrique",
        "STF": "Traçage électrique (circuits nucléaires)",
        "STV": "Traçage vapeur",
        "SVA": "Distribution de vapeur auxiliaire",
        "SVT": "Transformateur de vapeur",
        "TEG": "Effluents gazeux",
        "TEK": "Contrôle et rejet des effluents de l'îlot nucléaire",
        "TEN": "Circuits d'échantillonnage des effluents du BTE",
        "TEP": "Effluents liquides primaires",
        "TER": "Réservoir complémentaire de santé",
        "TES": "Effluents solides - tranche",
        "TEU": "Effluents liquides usés",
        "TRI": "Réfrigération intermédiaire traitement des effluents",
        "VDA": "Décharge atmosphère",
        "VPU": "Purges de conditionnement des circuits vapeur",
        "VRD": "Vapeur resurchauffée et désurchauffée",
        "VSC": "Soutirage vapeur S.B.T",
        "VSD": "Vapeur surchauffée et désurchauffe",
        "VVP": "Circuit vapeur principal, soupapes de mise à l'atmosphère et évents, vannes GV",
        "XCA": "Chaudière à fioul - chaudière électrique",
        "YBM": "Bras mort (instrumentation provisoire sur les tronçons inter-isolements)",
        "YGV": "Dispositif d'instrumentation GV",
    }
)

KNOWN_ECS_CODES = MappingProxyType(
    {**FUNCTIONAL_SET_CODES, **ELEMENTARY_SYSTEM_FAMILIES, **ELEMENTARY_SYSTEM_CODES}
)


def normalize_ecs_code(code: str) -> str:
    """Normalize a user-provided ECS code before lookup."""

    return code.strip().upper().replace(" ", "")


def describe_ecs_code(code: str) -> str | None:
    """Return the ECS label associated with ``code`` if it exists."""

    return KNOWN_ECS_CODES.get(normalize_ecs_code(code))

