site_name: parc
repo_url: https://github.com/lakodo/parc
site_url: https://lako.do/parc
site_description: Wrap dask scheduler to make it easy to buid datascience flow
site_author: Joris GUERRY
edit_uri: edit/main/docs/
repo_name: lakodo/parc
copyright: Maintained by <a href="https://9h.gg">Joris GUERRY</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        # python:
        #   setup_commands:
        #     - import sys
        #     - sys.path.append('../')
        python:
          options:
            extensions:
              - griffe_typingdoc
            show_root_heading: true
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
              - "!^_"
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lakodo/parc
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/parc

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
